# Generated by Django 4.0.4 on 2022-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_location_options_alter_image_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
