# Generated by Django 4.0.4 on 2022-05-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_image_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pub_date'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
